version: 0.2

phases:

  build:
    commands:
      - docker build -t brain-tasks-app:latest .
      - docker tag brain-tasks:$TAG 263336852738.dkr.ecr.ap-south-1.amazonaws.com/ brain-tasks-app:latest
  post_build:
    commands:
      - docker push 263336852738.dkr.ecr.ap-south-1.amazonaws.com/ brain-tasks-app:latest
