phases:
  pre_build:
    commands:
      - echo "Logging in to DockerHub..."
      - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t brain-tasks-app:latest .
