apiVersion: v1
kind: Service
metadata:
  name: brain-tasks-service
spec:
  type: LoadBalancer
  selector:
    app: brain-tasks     # ← Match this to deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
